cluster_size = 3

[[nodes]]
id = 1
address = "localhost:5001"

[[nodes]]
id = 2
address = "localhost:5002"

[[nodes]]
id = 3
address = "localhost:5003"

# [[nodes]]
# id = 4
# address = "localhost:5004"

# [[nodes]]
# id = 5
# address = "localhost:5005"
